name: Rebuild ICS Files

on:
  push:
    paths:
      - 'data/master_events.txt'
  workflow_dispatch:

permissions:
  contents: write  # ✅ REQUIRED for GITHUB_TOKEN to allow git push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run calendar builder
        run: python calendar_builder.py

      - name: Commit and push
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add output/
          git commit -m "🔄 Auto-update .ics and .txt files" || echo "No changes"
          git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git HEAD:${{ github.ref_name }}
