name: Build ICS Feeds

on:
  push:
    paths:
      - 'data/master_events.txt'
      - 'calendar_builder.py'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ics

      - name: Run calendar builder
        run: python calendar_builder.py

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add output/
          git commit -m "🔄 Auto-update .ics and .txt files" || echo "No changes to commit"
          git push
